T_KEYWORD = 'keyword'
T_SYMBOL = 'symbol'
T_IDENTIFIER = 'identifier'
T_INT_CONST = 'integerConstant'
T_STRING_CONST = 'stringConstant'

K_CLASS = 'class'
K_METHOD = 'method'
K_FUNCTION = 'function'
K_CONSTRUCTOR = 'constructor'
K_INT = 'int'
K_BOOLEAN = 'boolean'
K_CHAR = 'char'
K_VOID = 'void'
K_VAR = 'var'
K_STATIC = 'static'
K_FIELD = 'field'
K_LET = 'let'
K_DO = 'do'
K_IF = 'if'
K_ELSE = 'else'
K_WHILE = 'while'
K_RETURN = 'return'
K_TRUE = 'true'
K_FALSE = 'false'
K_NULL = 'null'
K_THIS = 'this'
KEYWORDS = [K_CLASS, K_METHOD, K_FUNCTION, K_CONSTRUCTOR,
            K_INT, K_BOOLEAN, K_CHAR, K_VOID, 
            K_VAR, K_STATIC, K_FIELD, K_LET,
            K_DO, K_IF, K_ELSE, K_WHILE, K_RETURN,
            K_TRUE, K_FALSE, K_NULL, K_THIS ]
            
N_CLASS = 'class'
N_CLASS_VAR_DEC = 'classVarDec'
N_TYPE = 'type'
N_SUBROUTINE_DEC = 'subroutineDec'
N_PARAMETER_LIST = 'parameterList'
N_VAR_DEC = 'varDec'
N_STATEMENTS = 'statements'
N_DO_STMT = 'doStatement'
N_LET_STMT = 'letStatement'
N_WHILE_STMT = 'whileStatement'
N_RETURN_STMT = 'returnStatement'
N_IF_STMT = 'ifStatement'
N_EXPRESSION = 'expression'
N_TERM = 'term'
N_BRACKETS = 'brackets'
N_EXPRESSION_LIST = 'expressionList'
N_SUBROUTINE_CALL = 'subroutineCall'

